-- Generated from src/engine/businessBoard.ts (scripts/print-catalog-sql.ts). Keys/names only.
insert into public.board_properties (rules_version, property_key, name, property_group) values
  ('BUSINESS_V1', 'MUMBAI', 'Mumbai', 'BLUE'),
  ('BUSINESS_V1', 'AHMEDABAD', 'Ahmedabad', 'BLUE'),
  ('BUSINESS_V1', 'CALCUTTA', 'Calcutta', 'BLUE'),
  ('BUSINESS_V1', 'HYDERABAD', 'Hyderabad', 'BLUE'),
  ('BUSINESS_V1', 'DARJEELING', 'Darjeeling', 'BLUE'),
  ('BUSINESS_V1', 'SIMLA', 'Simla', 'PURPLE'),
  ('BUSINESS_V1', 'MADRAS', 'Madras', 'PURPLE'),
  ('BUSINESS_V1', 'AMRITSAR', 'Amritsar', 'PURPLE'),
  ('BUSINESS_V1', 'SRINAGAR', 'Srinagar', 'PURPLE'),
  ('BUSINESS_V1', 'BANGALORE', 'Bangalore', 'PURPLE'),
  ('BUSINESS_V1', 'INDORE', 'Indore', 'GREEN'),
  ('BUSINESS_V1', 'AGRA', 'Agra', 'GREEN'),
  ('BUSINESS_V1', 'KANPUR', 'Kanpur', 'GREEN'),
  ('BUSINESS_V1', 'PATNA', 'Patna', 'GREEN'),
  ('BUSINESS_V1', 'JAIPUR', 'Jaipur', 'GREEN'),
  ('BUSINESS_V1', 'DELHI', 'Delhi', 'PINK'),
  ('BUSINESS_V1', 'CHANDIGARH', 'Chandigarh', 'PINK'),
  ('BUSINESS_V1', 'COCHIN', 'Cochin', 'PINK'),
  ('BUSINESS_V1', 'OOTACAMUND', 'Ootacamund', 'PINK'),
  ('BUSINESS_V1', 'MARGOA', 'Margoa', 'PINK'),
  ('BUSINESS_V1', 'RAILWAY', 'Railway', 'TRANSPORT_UTILITY'),
  ('BUSINESS_V1', 'AIR_INDIA', 'Air India', 'TRANSPORT_UTILITY'),
  ('BUSINESS_V1', 'MOTOR_BOAT', 'Motor Boat', 'TRANSPORT_UTILITY'),
  ('BUSINESS_V1', 'BEST', 'BEST', 'TRANSPORT_UTILITY'),
  ('BUSINESS_V1', 'ELECTRIC_COMPANY', 'Electric Company', 'TRANSPORT_UTILITY'),
  ('BUSINESS_V1', 'WATER_WORKS', 'Water Works', 'TRANSPORT_UTILITY')
on conflict (rules_version, property_key) do update set name = excluded.name, property_group = excluded.property_group;
